# services:
#   db:
#     container_name: fb_db
#     image: postgres:15.3-alpine3.18
#     restart: always
#     command: postgres -c 'max_connections=500'
#     networks:
#       - backend
#     hostname: postgresql
#     environment:
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - fb_pgdata:/var/lib/postgresql/data
#     ports:
#       - "${DB_PORT}:5432"
#     healthcheck:
#       test: pg_isready -U postgres
#       interval: 2s
#       timeout: 3s
#       retries: 40
version: '3.9'

services:
  database:
    container_name: db
    image: postgres:16.2-alpine3.18
    restart: always
    hostname: postgresql
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - fb_pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_NAME}
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  fb_pgdata:

# env_file:
#   - ../.env
    # networks:
    #   backend:
    #     name: backend
